### ISSUE TITLE
Buildpack error on Heroku

### ISSUE THREAD

**Issue by cuongnguyen2811** [praveen28624/oracle#1]
I got this error log when deploy on Heroku:
-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

**Comment by praveen28624** [comment]
error fixed. try now
